--���̺� ��ü ����
--������ ���
CREATE TABLE RECIPE 
(
  HITS NUMBER(6, 0) 
, RECIPESEQ NUMBER(6, 0) NOT NULL
, CATEGORY1 VARCHAR2(90 CHAR) 
, CATEGORY2 VARCHAR2(90 CHAR) 
, FOOD VARCHAR2(300 CHAR) 
, IMAGE VARCHAR2(3000 CHAR) 
, INGREDIENT VARCHAR2(3000 CHAR) 
, RECIPE VARCHAR2(3000 CHAR) 
);
--������ ī�װ� ���
CREATE TABLE RECIPECATEGORY 
(
  MAINCATEGORY VARCHAR2(30 BYTE) 
, SUBCATEGORY VARCHAR2(20 BYTE) 
, CATEGORYNUM NUMBER(6, 0)
);