--테이블 전체 모음
--레시피 등록
CREATE TABLE RECIPE 
(
  HITS NUMBER(6, 0) 
, RECIPE_SEQ NUMBER(6, 0) NOT NULL 
, CATEGORY1 VARCHAR2(90 CHAR) 
, CATEGORY2 VARCHAR2(90 CHAR) 
, FOOD VARCHAR2(300 CHAR) 
, IMAGE VARCHAR2(3000 CHAR) 
, INGREDIENT VARCHAR2(3000 CHAR) 
, RECIPE VARCHAR2(3000 CHAR) 
);
--관리자 카테고리 등록
CREATE TABLE RECIPECATEGORY 
(
  MAINCATEGORY VARCHAR2(30 BYTE) 
, SUBCATEGORY VARCHAR2(20 BYTE) 
, CATEGORYNUM NUMBER(6, 0)
);