--테이블 전체 모음
--레시피 등록
CREATE TABLE RECIPE 
(
  RECIPE_SEQ NUMBER(6, 0) 
, CATEGORY1 VARCHAR2(90 BYTE) 
, CATEGORY2 VARCHAR2(90 BYTE) 
, IMAGE VARCHAR2(300 BYTE) 
, FOOD VARCHAR2(30 BYTE) 
, INGREDIENT VARCHAR2(1500 BYTE) 
, RECIPE VARCHAR2(1500 BYTE) 
, HITS VARCHAR2(450 BYTE) 
);
--관리자 카테고리 등록
CREATE TABLE RECIPECATEGORY 
(
  MAINCATEGORY VARCHAR2(30 BYTE) 
, SUBCATEGORY VARCHAR2(20 BYTE) 
, CATEGORYNUM NUMBER(6, 0)
);